package ch.adibilis.jtg.writer;

import ch.adibilis.jtg.config.GeneratorConfig;
import ch.adibilis.jtg.model.endpoints.Endpoint;
import ch.adibilis.jtg.model.types.*;
import ch.adibilis.jtg.validation.Validation;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class TypeScriptTypeWriterTest {

    private GeneratorConfig config;

    @BeforeEach
    void setUp() {
        config = new GeneratorConfig(
                List.of("com.example"), List.of("/out"), false, "", null, Map.of(), List.of(), 0
        );
    }

    @Test
    void generatesSimpleInterface() {
        ObjectType user = new ObjectType("UserResponse", "user", List.of());
        user.setFields(List.of(
                new Field("name", PrimitiveType.String),
                new Field("age", PrimitiveType.Int)
        ));

        Map<String, Type> types = new LinkedHashMap<>();
        types.put("UserResponse", user);

        TypeScriptTypeWriter writer = new TypeScriptTypeWriter();
        List<TypeScriptFile> files = writer.generateTypes(types, config);

        assertThat(files).hasSize(1);
        TypeScriptFile file = files.get(0);
        assertThat(file.getRelativePath()).isEqualTo("types/user/UserResponse.ts");
        assertThat(file.getBody()).contains("export interface UserResponse {");
        assertThat(file.getBody()).contains("    name: string;");
        assertThat(file.getBody()).contains("    age: number;");
    }

    @Test
    void generatesInterfaceWithOptionalField() {
        ObjectType obj = new ObjectType("Dto", "common", List.of());
        obj.setFields(List.of(
                new Field("required", PrimitiveType.String, true),
                new Field("optional", PrimitiveType.String, false)
        ));

        Map<String, Type> types = new LinkedHashMap<>();
        types.put("Dto", obj);

        TypeScriptTypeWriter writer = new TypeScriptTypeWriter();
        List<TypeScriptFile> files = writer.generateTypes(types, config);

        assertThat(files.get(0).getBody()).contains("    required: string;");
        assertThat(files.get(0).getBody()).contains("    optional?: string;");
    }

    @Test
    void generatesGenericInterface() {
        ObjectType obj = new ObjectType("Response", "common", List.of("T"));
        obj.setFields(List.of(
                new Field("data", new TypeVar("T")),
                new Field("count", PrimitiveType.Int)
        ));

        Map<String, Type> types = new LinkedHashMap<>();
        types.put("Response", obj);

        TypeScriptTypeWriter writer = new TypeScriptTypeWriter();
        List<TypeScriptFile> files = writer.generateTypes(types, config);

        assertThat(files.get(0).getBody()).contains("export interface Response<T> {");
        assertThat(files.get(0).getBody()).contains("    data: T;");
    }

    @Test
    void generatesEnumWithConstArray() {
        EnumType status = new EnumType("Status", List.of("ACTIVE", "INACTIVE", "PENDING"), "common");

        Map<String, Type> types = new LinkedHashMap<>();
        types.put("Status", status);

        TypeScriptTypeWriter writer = new TypeScriptTypeWriter();
        List<TypeScriptFile> files = writer.generateTypes(types, config);

        assertThat(files.get(0).getBody()).contains("export const StatusValues = ['ACTIVE', 'INACTIVE', 'PENDING'] as const;");
        assertThat(files.get(0).getBody()).contains("export type Status = typeof StatusValues[number];");
    }

    @Test
    void generatesUnionType() {
        ObjectType dog = new ObjectType("Dog", "animals", List.of());
        ObjectType cat = new ObjectType("Cat", "animals", List.of());
        UnionType animal = new UnionType("Animal", List.of(dog, cat), "animals", "type");

        Map<String, Type> types = new LinkedHashMap<>();
        types.put("Animal", animal);

        TypeScriptTypeWriter writer = new TypeScriptTypeWriter();
        List<TypeScriptFile> files = writer.generateTypes(types, config);

        TypeScriptFile animalFile = files.stream()
                .filter(f -> f.getRelativePath().contains("Animal"))
                .findFirst().orElseThrow();
        assertThat(animalFile.getBody()).contains("export type Animal = Dog | Cat;");
    }

    @Test
    void includesFileHeader() {
        ObjectType obj = new ObjectType("Dto", "common", List.of());
        obj.setFields(List.of());

        Map<String, Type> types = new LinkedHashMap<>();
        types.put("Dto", obj);

        TypeScriptTypeWriter writer = new TypeScriptTypeWriter();
        List<TypeScriptFile> files = writer.generateTypes(types, config);

        assertThat(files.get(0).getBody()).startsWith("// Generated by Adibilis Java Type Generator\n");
    }

    @Test
    void includesHeaderSuffix() {
        GeneratorConfig suffixConfig = new GeneratorConfig(
                List.of("com.example"), List.of("/out"), false,
                " — do not edit manually", null, Map.of(), List.of(), 0
        );
        ObjectType obj = new ObjectType("Dto", "common", List.of());
        obj.setFields(List.of());

        Map<String, Type> types = new LinkedHashMap<>();
        types.put("Dto", obj);

        TypeScriptTypeWriter writer = new TypeScriptTypeWriter();
        List<TypeScriptFile> files = writer.generateTypes(types, suffixConfig);

        assertThat(files.get(0).getBody()).startsWith("// Generated by Adibilis Java Type Generator — do not edit manually\n");
    }

    @Test
    void generatesImportsForReferencedTypes() {
        ObjectType address = new ObjectType("Address", "common", List.of());
        address.setFields(List.of(new Field("street", PrimitiveType.String)));

        ObjectType user = new ObjectType("User", "user", List.of());
        user.setFields(List.of(
                new Field("name", PrimitiveType.String),
                new Field("address", address)
        ));

        Map<String, Type> types = new LinkedHashMap<>();
        types.put("Address", address);
        types.put("User", user);

        TypeScriptTypeWriter writer = new TypeScriptTypeWriter();
        List<TypeScriptFile> files = writer.generateTypes(types, config);

        TypeScriptFile userFile = files.stream()
                .filter(f -> f.getRelativePath().contains("User"))
                .findFirst().orElseThrow();
        assertThat(userFile.getImports()).isNotEmpty();
        assertThat(userFile.getImports().get(0).namedImports()).contains("Address");
    }
}
