package ch.adibilis.jtg.zod;

import ch.adibilis.jtg.config.GeneratorConfig;
import ch.adibilis.jtg.model.types.*;
import ch.adibilis.jtg.validation.Validation;
import ch.adibilis.jtg.writer.*;

import java.util.*;
import java.util.stream.Collectors;

public class ZodTypeWriter implements Writer {

    private static final String HEADER = "// Generated by Adibilis Java Type Generator";

    @Override
    public boolean handlesTypes() { return true; }

    @Override
    public List<TypeScriptFile> generate(GeneratorContext context) {
        Map<String, Type> namedTypes = context.namedTypes();
        GeneratorConfig config = context.config();

        // Split into: validated objects (Zod), enums (Zod), and plain TS types
        Map<String, Type> zodObjectTypes = new LinkedHashMap<>();
        Map<String, Type> zodEnumTypes = new LinkedHashMap<>();
        Map<String, Type> plainTypes = new LinkedHashMap<>();

        for (Map.Entry<String, Type> entry : namedTypes.entrySet()) {
            Type type = entry.getValue();
            if (type instanceof ObjectType obj && hasValidations(obj)) {
                zodObjectTypes.put(entry.getKey(), type);
            } else if (type instanceof EnumType) {
                zodEnumTypes.put(entry.getKey(), type);
            } else {
                plainTypes.put(entry.getKey(), type);
            }
        }

        // Generate Zod schemas for validated object types.
        List<TypeScriptFile> zodFiles = new ArrayList<>();
        for (Map.Entry<String, Type> entry : zodObjectTypes.entrySet()) {
            if (entry.getValue() instanceof ObjectType obj) {
                zodFiles.add(generateZodObject(obj, config));
            }
        }

        // Generate Zod enums.
        for (Map.Entry<String, Type> entry : zodEnumTypes.entrySet()) {
            if (entry.getValue() instanceof EnumType e) {
                zodFiles.add(generateZodEnum(e, config));
            }
        }

        // Build the Zod-emitted file map before TypeScriptTypeWriter runs so plain
        // DTOs that reference an enum or a validated schema can be resolved against
        // it (named imports, since Zod files carry no default export).
        Map<String, TypeScriptFile> zodFileByName = new LinkedHashMap<>();
        for (TypeScriptFile f : zodFiles) {
            zodFileByName.put(extractTypeName(f.getRelativePath()), f);
        }

        // Resolve cross-references between Zod files and render every Zod file's
        // registered imports into its body. Without this pass, `z` and any
        // referenced `<Name>Model` symbols would be undefined at runtime.
        for (TypeScriptFile f : zodFiles) {
            Type sourceType = namedTypes.get(extractTypeName(f.getRelativePath()));
            if (sourceType instanceof ObjectType obj) {
                resolveModelImports(f, obj, zodFileByName);
            }
            renderImportsIntoBody(f);
        }

        List<TypeScriptFile> files = new ArrayList<>();

        // Generate plain TS for non-validated types. Pass the Zod-emitted files
        // as external named-import targets so plain DTOs that reference enums
        // (e.g. `LeadStatusUpdateRequest.status: LeadStatus`) get proper
        // `import { LeadStatus } from '...'` statements.
        TypeScriptTypeWriter tsWriter = new TypeScriptTypeWriter();
        files.addAll(tsWriter.generateTypes(plainTypes, config, zodFileByName));

        files.addAll(zodFiles);
        return files;
    }

    private boolean hasValidations(ObjectType obj) {
        return obj.getFields().stream().anyMatch(f -> !f.validations().isEmpty());
    }

    private TypeScriptFile generateZodObject(ObjectType obj, GeneratorConfig config) {
        TypeScriptFile file = new TypeScriptFile("types/" + obj.getPackageSegment() + "/" + obj.getName() + ".ts");
        file.getImports().add(new TypeScriptFile.Import("zod", null, Set.of("z")));

        StringBuilder body = new StringBuilder();
        body.append(header(config)).append("\n\n");

        body.append("export const ").append(obj.getName()).append("Model = z.object({\n");

        for (Field field : obj.getFields()) {
            body.append("    ").append(field.name()).append(": ");
            body.append(zodField(field, config));
            body.append(",\n");
        }

        body.append("});\n\n");
        body.append("export type ").append(obj.getName())
                .append(" = z.infer<typeof ").append(obj.getName()).append("Model>;\n");

        file.setBody(body.toString());
        return file;
    }

    private String zodField(Field field, GeneratorConfig config) {
        StringBuilder sb = new StringBuilder();
        sb.append(zodType(field.type(), config));

        // Append validation chains
        for (Validation v : field.validations()) {
            sb.append(zodValidation(v));
        }

        // Optional/nullable for non-required fields
        if (!field.required()) {
            sb.append(".optional().nullable()");
        }

        return sb.toString();
    }

    private String zodType(Type type, GeneratorConfig config) {
        return switch (type) {
            case PrimitiveType p -> zodPrimitive(p);
            case ArrayType a -> "z.array(" + zodNestedType(a.subType(), config) + ")";
            case MapType m -> "z.record(" + zodNestedType(m.keyType(), config) + ", " + zodNestedType(m.valueType(), config) + ")";
            case OptionalType o -> zodType(o.subType(), config) + ".optional().nullable()";
            case EnumType e -> "z.enum([" + e.values().stream().map(v -> "'" + v + "'").collect(Collectors.joining(", ")) + "])";
            case ObjectType o -> o.getName() + "Model";
            case TypeVar t -> "z.any()";
            default -> "z.any()";
        };
    }

    /**
     * Zod type expression for use in nested positions (array elements, map key/value).
     * For Int, uses z.number() without .int() constraint since no field-level validations apply here.
     */
    private String zodNestedType(Type type, GeneratorConfig config) {
        return switch (type) {
            case PrimitiveType p -> zodPrimitiveNested(p);
            case ArrayType a -> "z.array(" + zodNestedType(a.subType(), config) + ")";
            case MapType m -> "z.record(" + zodNestedType(m.keyType(), config) + ", " + zodNestedType(m.valueType(), config) + ")";
            case OptionalType o -> zodNestedType(o.subType(), config) + ".optional().nullable()";
            case EnumType e -> "z.enum([" + e.values().stream().map(v -> "'" + v + "'").collect(Collectors.joining(", ")) + "])";
            case ObjectType o -> o.getName() + "Model";
            case TypeVar t -> "z.any()";
            default -> "z.any()";
        };
    }

    private String zodPrimitive(PrimitiveType p) {
        return switch (p) {
            case Int -> "z.number().int()";
            case Double -> "z.number()";
            case BigInt -> "z.bigint()";
            case String, Date, LocalDate -> "z.string()";
            case Boolean -> "z.boolean()";
            case File -> "z.instanceof(File)";
            case Void -> "z.void()";
            case Unknown -> "z.unknown()";
        };
    }

    private String zodPrimitiveNested(PrimitiveType p) {
        return switch (p) {
            case Int -> "z.number()";
            case Double -> "z.number()";
            case BigInt -> "z.bigint()";
            case String, Date, LocalDate -> "z.string()";
            case Boolean -> "z.boolean()";
            case File -> "z.instanceof(File)";
            case Void -> "z.void()";
            case Unknown -> "z.unknown()";
        };
    }

    private String zodValidation(Validation v) {
        return switch (v) {
            case Validation.Min m -> ".min(" + m.value() + withMessage(m.message()) + ")";
            case Validation.Max m -> ".max(" + m.value() + withMessage(m.message()) + ")";
            case Validation.Size s -> ".min(" + s.min() + ").max(" + s.max() + ")";
            case Validation.NotBlank n -> ".regex(/.+/)";
            case Validation.Pattern p -> ".regex(/" + p.regexp() + "/)";
            case Validation.Email e -> ".email(" + messageArg(e.message()) + ")";
        };
    }

    private String withMessage(String message) {
        if (message == null || message.isEmpty()) return "";
        return ", { message: \"" + message + "\" }";
    }

    private String messageArg(String message) {
        if (message == null || message.isEmpty()) return "";
        return "{ message: \"" + message + "\" }";
    }

    private TypeScriptFile generateZodEnum(EnumType e, GeneratorConfig config) {
        TypeScriptFile file = new TypeScriptFile("types/" + e.packageSegment() + "/" + e.name() + ".ts");
        file.getImports().add(new TypeScriptFile.Import("zod", null, Set.of("z")));

        StringBuilder body = new StringBuilder();
        body.append(header(config)).append("\n\n");

        String values = e.values().stream().map(v -> "'" + v + "'").collect(Collectors.joining(", "));
        body.append("export const ").append(e.name()).append("Model = z.enum([").append(values).append("]);\n");
        body.append("export type ").append(e.name())
                .append(" = z.infer<typeof ").append(e.name()).append("Model>;\n");

        file.setBody(body.toString());
        return file;
    }

    /**
     * Walks a validated object's fields and registers a named import for every
     * cross-reference to another Zod-emitted schema ({@code <Name>Model}).
     * <p>
     * Limitation: references to plain (non-validated) object types are *not*
     * registered — the schema body emits {@code <Name>Model} but no such symbol
     * exists in the plain file. To keep a Zod subtree compilable, every
     * cross-referenced ObjectType must also carry at least one validation
     * (or be promoted otherwise). Enums in field position are inlined as
     * {@code z.enum([...])}, so they need no import.
     */
    private void resolveModelImports(TypeScriptFile file, ObjectType obj, Map<String, TypeScriptFile> zodFileByName) {
        Set<String> referenced = new LinkedHashSet<>();
        for (Field field : obj.getFields()) {
            collectObjectReferences(field.type(), referenced);
        }
        for (String name : referenced) {
            if (name.equals(obj.getName())) continue;
            TypeScriptFile target = zodFileByName.get(name);
            if (target == null) continue;
            String importPath = file.resolveImportPath(target);
            file.getImports().add(new TypeScriptFile.Import(importPath, null, Set.of(name + "Model")));
        }
    }

    private void collectObjectReferences(Type type, Set<String> out) {
        switch (type) {
            case ObjectType o -> out.add(o.getName());
            case ArrayType a -> collectObjectReferences(a.subType(), out);
            case MapType m -> {
                collectObjectReferences(m.keyType(), out);
                collectObjectReferences(m.valueType(), out);
            }
            case OptionalType o -> collectObjectReferences(o.subType(), out);
            default -> {}
        }
    }

    private void renderImportsIntoBody(TypeScriptFile file) {
        if (file.getImports().isEmpty()) return;

        StringBuilder importBlock = new StringBuilder();
        for (TypeScriptFile.Import imp : file.getImports()) {
            if (imp.defaultImport() != null && !imp.defaultImport().isEmpty()) {
                importBlock.append("import ").append(imp.defaultImport())
                        .append(" from '").append(imp.path()).append("';\n");
            } else if (imp.namedImports() != null && !imp.namedImports().isEmpty()) {
                importBlock.append("import { ").append(String.join(", ", imp.namedImports()))
                        .append(" } from '").append(imp.path()).append("';\n");
            }
        }

        // Insert imports after the header line so the generator comment stays on top.
        String body = file.getBody();
        int headerEnd = body.indexOf('\n');
        if (headerEnd >= 0) {
            file.setBody(body.substring(0, headerEnd + 1) + importBlock + body.substring(headerEnd + 1));
        }
    }

    private String extractTypeName(String relativePath) {
        String fileName = relativePath.substring(relativePath.lastIndexOf('/') + 1);
        return fileName.replace(".ts", "");
    }

    private String header(GeneratorConfig config) {
        return HEADER + config.headerSuffix();
    }
}
