package ch.adibilis.jtg.zod;

import ch.adibilis.jtg.config.GeneratorConfig;
import ch.adibilis.jtg.model.types.*;
import ch.adibilis.jtg.validation.Validation;
import ch.adibilis.jtg.writer.*;

import java.util.*;
import java.util.stream.Collectors;

public class ZodTypeWriter implements Writer {

    private static final String HEADER = "// Generated by Adibilis Java Type Generator";

    @Override
    public boolean handlesTypes() { return true; }

    @Override
    public List<TypeScriptFile> generate(GeneratorContext context) {
        Map<String, Type> namedTypes = context.namedTypes();
        GeneratorConfig config = context.config();

        // Split into: validated objects (Zod), enums (Zod), and plain TS types
        Map<String, Type> zodObjectTypes = new LinkedHashMap<>();
        Map<String, Type> zodEnumTypes = new LinkedHashMap<>();
        Map<String, Type> plainTypes = new LinkedHashMap<>();

        for (Map.Entry<String, Type> entry : namedTypes.entrySet()) {
            Type type = entry.getValue();
            if (type instanceof ObjectType obj && hasValidations(obj)) {
                zodObjectTypes.put(entry.getKey(), type);
            } else if (type instanceof EnumType) {
                zodEnumTypes.put(entry.getKey(), type);
            } else {
                plainTypes.put(entry.getKey(), type);
            }
        }

        List<TypeScriptFile> files = new ArrayList<>();

        // Generate plain TS for non-validated types (non-enum, non-validated objects)
        TypeScriptTypeWriter tsWriter = new TypeScriptTypeWriter();
        files.addAll(tsWriter.generateTypes(plainTypes, config));

        // Generate Zod schemas for validated object types
        for (Map.Entry<String, Type> entry : zodObjectTypes.entrySet()) {
            if (entry.getValue() instanceof ObjectType obj) {
                files.add(generateZodObject(obj, config));
            }
        }

        // Generate Zod enums
        for (Map.Entry<String, Type> entry : zodEnumTypes.entrySet()) {
            if (entry.getValue() instanceof EnumType e) {
                files.add(generateZodEnum(e, config));
            }
        }

        return files;
    }

    private boolean hasValidations(ObjectType obj) {
        return obj.getFields().stream().anyMatch(f -> !f.validations().isEmpty());
    }

    private TypeScriptFile generateZodObject(ObjectType obj, GeneratorConfig config) {
        TypeScriptFile file = new TypeScriptFile("types/" + obj.getPackageSegment() + "/" + obj.getName() + ".ts");
        file.getImports().add(new TypeScriptFile.Import("zod", null, Set.of("z")));

        StringBuilder body = new StringBuilder();
        body.append(header(config)).append("\n\n");

        body.append("export const ").append(obj.getName()).append("Model = z.object({\n");

        for (Field field : obj.getFields()) {
            body.append("    ").append(field.name()).append(": ");
            body.append(zodField(field, config));
            body.append(",\n");
        }

        body.append("});\n\n");
        body.append("export type ").append(obj.getName())
                .append(" = z.infer<typeof ").append(obj.getName()).append("Model>;\n");

        file.setBody(body.toString());
        return file;
    }

    private String zodField(Field field, GeneratorConfig config) {
        StringBuilder sb = new StringBuilder();
        sb.append(zodType(field.type(), config));

        // Append validation chains
        for (Validation v : field.validations()) {
            sb.append(zodValidation(v));
        }

        // Optional/nullable for non-required fields
        if (!field.required()) {
            sb.append(".optional().nullable()");
        }

        return sb.toString();
    }

    private String zodType(Type type, GeneratorConfig config) {
        return switch (type) {
            case PrimitiveType p -> zodPrimitive(p);
            case ArrayType a -> "z.array(" + zodNestedType(a.subType(), config) + ")";
            case MapType m -> "z.record(" + zodNestedType(m.keyType(), config) + ", " + zodNestedType(m.valueType(), config) + ")";
            case OptionalType o -> zodType(o.subType(), config) + ".optional().nullable()";
            case EnumType e -> "z.enum([" + e.values().stream().map(v -> "'" + v + "'").collect(Collectors.joining(", ")) + "])";
            case ObjectType o -> o.getName() + "Model";
            case TypeVar t -> "z.any()";
            default -> "z.any()";
        };
    }

    /**
     * Zod type expression for use in nested positions (array elements, map key/value).
     * For Int, uses z.number() without .int() constraint since no field-level validations apply here.
     */
    private String zodNestedType(Type type, GeneratorConfig config) {
        return switch (type) {
            case PrimitiveType p -> zodPrimitiveNested(p);
            case ArrayType a -> "z.array(" + zodNestedType(a.subType(), config) + ")";
            case MapType m -> "z.record(" + zodNestedType(m.keyType(), config) + ", " + zodNestedType(m.valueType(), config) + ")";
            case OptionalType o -> zodNestedType(o.subType(), config) + ".optional().nullable()";
            case EnumType e -> "z.enum([" + e.values().stream().map(v -> "'" + v + "'").collect(Collectors.joining(", ")) + "])";
            case ObjectType o -> o.getName() + "Model";
            case TypeVar t -> "z.any()";
            default -> "z.any()";
        };
    }

    private String zodPrimitive(PrimitiveType p) {
        return switch (p) {
            case Int -> "z.number().int()";
            case Double -> "z.number()";
            case BigInt -> "z.bigint()";
            case String, Date -> "z.string()";
            case Boolean -> "z.boolean()";
            case File -> "z.instanceof(File)";
            case Void -> "z.void()";
        };
    }

    private String zodPrimitiveNested(PrimitiveType p) {
        return switch (p) {
            case Int -> "z.number()";
            case Double -> "z.number()";
            case BigInt -> "z.bigint()";
            case String, Date -> "z.string()";
            case Boolean -> "z.boolean()";
            case File -> "z.instanceof(File)";
            case Void -> "z.void()";
        };
    }

    private String zodValidation(Validation v) {
        return switch (v) {
            case Validation.Min m -> ".min(" + m.value() + withMessage(m.message()) + ")";
            case Validation.Max m -> ".max(" + m.value() + withMessage(m.message()) + ")";
            case Validation.Size s -> ".min(" + s.min() + ").max(" + s.max() + ")";
            case Validation.NotBlank n -> ".regex(/.+/)";
            case Validation.Pattern p -> ".regex(/" + p.regexp() + "/)";
            case Validation.Email e -> ".email(" + messageArg(e.message()) + ")";
        };
    }

    private String withMessage(String message) {
        if (message == null || message.isEmpty()) return "";
        return ", { message: \"" + message + "\" }";
    }

    private String messageArg(String message) {
        if (message == null || message.isEmpty()) return "";
        return "{ message: \"" + message + "\" }";
    }

    private TypeScriptFile generateZodEnum(EnumType e, GeneratorConfig config) {
        TypeScriptFile file = new TypeScriptFile("types/" + e.packageSegment() + "/" + e.name() + ".ts");
        file.getImports().add(new TypeScriptFile.Import("zod", null, Set.of("z")));

        StringBuilder body = new StringBuilder();
        body.append(header(config)).append("\n\n");

        String values = e.values().stream().map(v -> "'" + v + "'").collect(Collectors.joining(", "));
        body.append("export const ").append(e.name()).append("Model = z.enum([").append(values).append("]);\n");
        body.append("export type ").append(e.name())
                .append(" = z.infer<typeof ").append(e.name()).append("Model>;\n");

        file.setBody(body.toString());
        return file;
    }

    private String header(GeneratorConfig config) {
        return HEADER + config.headerSuffix();
    }
}
