package ch.adibilis.jtg.zod;

import ch.adibilis.jtg.config.GeneratorConfig;
import ch.adibilis.jtg.model.types.*;
import ch.adibilis.jtg.validation.Validation;
import ch.adibilis.jtg.writer.*;
import ch.adibilis.jtg.writer.TypeScriptTypeMapper;

import java.util.*;
import java.util.stream.Collectors;

public class ZodTypeWriter implements Writer {

    private static final String HEADER = "// Generated by Adibilis Java Type Generator";

    @Override
    public boolean handlesTypes() { return true; }

    @Override
    public List<TypeScriptFile> generate(GeneratorContext context) {
        Map<String, Type> namedTypes = context.namedTypes();
        GeneratorConfig config = context.config();

        // Split into: validated objects (Zod), enums (Zod), and plain TS types
        Map<String, Type> zodObjectTypes = new LinkedHashMap<>();
        Map<String, Type> zodEnumTypes = new LinkedHashMap<>();
        Map<String, Type> plainTypes = new LinkedHashMap<>();

        for (Map.Entry<String, Type> entry : namedTypes.entrySet()) {
            Type type = entry.getValue();
            if (type instanceof ObjectType obj && hasValidations(obj)) {
                zodObjectTypes.put(entry.getKey(), type);
            } else if (type instanceof EnumType) {
                zodEnumTypes.put(entry.getKey(), type);
            } else {
                plainTypes.put(entry.getKey(), type);
            }
        }

        promoteReferencedObjects(zodObjectTypes, plainTypes);

        // Generate Zod schemas for validated object types. The emitting ObjectType is
        // kept alongside its file: namedTypes is keyed by FULLY-QUALIFIED name in the
        // real parser (SpringReflectionParser.typeCache uses clazz.getName()), so a
        // later simple-name lookup silently misses and cross-reference imports are
        // never registered.
        List<TypeScriptFile> zodFiles = new ArrayList<>();
        Map<TypeScriptFile, ObjectType> objectByFile = new LinkedHashMap<>();
        for (Map.Entry<String, Type> entry : zodObjectTypes.entrySet()) {
            if (entry.getValue() instanceof ObjectType obj) {
                TypeScriptFile file = generateZodObject(obj, config);
                zodFiles.add(file);
                objectByFile.put(file, obj);
            }
        }

        // Generate Zod enums.
        for (Map.Entry<String, Type> entry : zodEnumTypes.entrySet()) {
            if (entry.getValue() instanceof EnumType e) {
                zodFiles.add(generateZodEnum(e, config));
            }
        }

        // Build the Zod-emitted file map before TypeScriptTypeWriter runs so plain
        // DTOs that reference an enum or a validated schema can be resolved against
        // it (named imports, since Zod files carry no default export).
        Map<String, TypeScriptFile> zodFileByName = new LinkedHashMap<>();
        for (TypeScriptFile f : zodFiles) {
            zodFileByName.put(extractTypeName(f.getRelativePath()), f);
        }

        // Resolve cross-references between Zod files and render every Zod file's
        // registered imports into its body. Without this pass, `z` and any
        // referenced `<Name>Model` symbols would be undefined at runtime.
        for (TypeScriptFile f : zodFiles) {
            ObjectType obj = objectByFile.get(f);
            if (obj != null) {
                resolveModelImports(f, obj, zodFileByName);
            }
            renderImportsIntoBody(f);
        }

        List<TypeScriptFile> files = new ArrayList<>();

        // Generate plain TS for non-validated types. Pass the Zod-emitted files
        // as external named-import targets so plain DTOs that reference enums
        // (e.g. `LeadStatusUpdateRequest.status: LeadStatus`) get proper
        // `import { LeadStatus } from '...'` statements.
        TypeScriptTypeWriter tsWriter = new TypeScriptTypeWriter();
        files.addAll(tsWriter.generateTypes(plainTypes, config, zodFileByName));

        files.addAll(zodFiles);
        return files;
    }

    private boolean hasValidations(ObjectType obj) {
        return obj.getFields().stream().anyMatch(f -> !f.validations().isEmpty());
    }

    /**
     * Moves every object type reachable from a Zod schema out of the plain-TS bucket
     * and into the Zod bucket, transitively.
     * <p>
     * {@link #zodType} renders any {@code ObjectType} in field position as
     * {@code <Name>Model}. A referenced DTO that carries no constraints of its own
     * would otherwise be emitted as a plain interface, which declares no such symbol,
     * so the referencing schema would not compile. Promoted types become
     * constraint-free {@code z.object({...})} schemas. Traversal is by name so a
     * self- or mutually-referential type terminates.
     */
    private void promoteReferencedObjects(Map<String, Type> zodObjectTypes, Map<String, Type> plainTypes) {
        Map<String, String> plainKeyByName = new LinkedHashMap<>();
        for (Map.Entry<String, Type> entry : plainTypes.entrySet()) {
            if (entry.getValue() instanceof ObjectType obj) {
                plainKeyByName.putIfAbsent(obj.getName(), entry.getKey());
            }
        }

        Deque<ObjectType> pending = new ArrayDeque<>();
        for (Type type : zodObjectTypes.values()) {
            if (type instanceof ObjectType obj) pending.add(obj);
        }

        Set<String> visited = new HashSet<>();
        while (!pending.isEmpty()) {
            ObjectType current = pending.poll();
            if (!visited.add(current.getName())) continue;

            Set<String> referenced = new LinkedHashSet<>();
            for (Field field : current.getFields()) {
                collectObjectReferences(field.type(), referenced);
            }

            for (String name : referenced) {
                String plainKey = plainKeyByName.get(name);
                if (plainKey == null) continue;
                Type promoted = plainTypes.remove(plainKey);
                if (promoted instanceof ObjectType obj) {
                    zodObjectTypes.put(plainKey, obj);
                    pending.add(obj);
                }
            }
        }
    }

    private TypeScriptFile generateZodObject(ObjectType obj, GeneratorConfig config) {
        TypeScriptFile file = new TypeScriptFile("types/" + obj.getPackageSegment() + "/" + obj.getName() + ".ts");
        file.getImports().add(new TypeScriptFile.Import("zod", null, Set.of("z")));

        StringBuilder body = new StringBuilder();
        body.append(header(config)).append("\n\n");

        // A schema that references itself cannot derive its type with z.infer off its own
        // initializer (TS7022 / TS2448). Zod's idiom is z.lazy() behind an explicit
        // z.ZodType<T>, which needs T declared up front rather than inferred.
        boolean recursive = isSelfReferential(obj);

        if (recursive) {
            body.append("export interface ").append(obj.getName()).append(" {\n");
            for (Field field : obj.getFields()) {
                boolean optional = !field.required() && !hasPresenceConstraint(field);
                body.append("    ").append(field.name()).append(optional ? "?" : "").append(": ")
                        .append(TypeScriptTypeMapper.map(field.type(), config))
                        .append(optional ? " | null" : "").append(";\n");
            }
            body.append("}\n\n");

            body.append("export const ").append(obj.getName())
                    .append("Model: z.ZodType<").append(obj.getName()).append("> = z.lazy(() => z.object({\n");
        } else {
            body.append("export const ").append(obj.getName()).append("Model = z.object({\n");
        }

        for (Field field : obj.getFields()) {
            body.append("    ").append(field.name()).append(": ");
            body.append(zodField(field, config));
            body.append(",\n");
        }

        if (recursive) {
            body.append("}));\n");
        } else {
            body.append("});\n\n");
            body.append("export type ").append(obj.getName())
                    .append(" = z.infer<typeof ").append(obj.getName()).append("Model>;\n");
        }

        file.setBody(body.toString());
        return file;
    }

    private boolean isSelfReferential(ObjectType obj) {
        Set<String> referenced = new LinkedHashSet<>();
        for (Field field : obj.getFields()) {
            collectObjectReferences(field.type(), referenced);
        }
        return referenced.contains(obj.getName());
    }

    private String zodField(Field field, GeneratorConfig config) {
        StringBuilder sb = new StringBuilder();
        sb.append(zodType(field.type(), config));

        // Append validation chains
        for (Validation v : field.validations()) {
            sb.append(zodValidation(v));
        }

        // A presence constraint beats the nullability flag. Field.required() is derived
        // from @Nullable alone, but DTOs routinely carry `@NotBlank private @Nullable
        // String x` — @Nullable is for IDE null-analysis, the constraint is the contract.
        // Emitting .optional() there makes the schema fail OPEN: parse({}) would succeed
        // on a required field, since .optional() short-circuits the whole chain.
        if (!field.required() && !hasPresenceConstraint(field)) {
            sb.append(".optional().nullable()");
        }

        return sb.toString();
    }

    private boolean hasPresenceConstraint(Field field) {
        return field.validations().stream().anyMatch(v ->
                v instanceof Validation.NotBlank
                        || v instanceof Validation.NotNull
                        || v instanceof Validation.NotEmpty);
    }

    private String zodType(Type type, GeneratorConfig config) {
        return switch (type) {
            case PrimitiveType p -> zodPrimitive(p);
            case ArrayType a -> "z.array(" + zodNestedType(a.subType(), config) + ")";
            case MapType m -> "z.record(" + zodNestedType(m.keyType(), config) + ", " + zodNestedType(m.valueType(), config) + ")";
            case OptionalType o -> zodType(o.subType(), config) + ".optional().nullable()";
            case EnumType e -> "z.enum([" + e.values().stream().map(v -> "'" + v + "'").collect(Collectors.joining(", ")) + "])";
            case ObjectType o -> o.getName() + "Model";
            case TypeVar t -> "z.any()";
            default -> "z.any()";
        };
    }

    /**
     * Zod type expression for use in nested positions (array elements, map key/value).
     * For Int, uses z.number() without .int() constraint since no field-level validations apply here.
     */
    private String zodNestedType(Type type, GeneratorConfig config) {
        return switch (type) {
            case PrimitiveType p -> zodPrimitiveNested(p);
            case ArrayType a -> "z.array(" + zodNestedType(a.subType(), config) + ")";
            case MapType m -> "z.record(" + zodNestedType(m.keyType(), config) + ", " + zodNestedType(m.valueType(), config) + ")";
            case OptionalType o -> zodNestedType(o.subType(), config) + ".optional().nullable()";
            case EnumType e -> "z.enum([" + e.values().stream().map(v -> "'" + v + "'").collect(Collectors.joining(", ")) + "])";
            case ObjectType o -> o.getName() + "Model";
            case TypeVar t -> "z.any()";
            default -> "z.any()";
        };
    }

    private String zodPrimitive(PrimitiveType p) {
        return switch (p) {
            case Int -> "z.number().int()";
            case Double -> "z.number()";
            case BigInt -> "z.bigint()";
            case String, Date, LocalDate -> "z.string()";
            case Boolean -> "z.boolean()";
            case File -> "z.instanceof(File)";
            case Void -> "z.void()";
            case Unknown -> "z.unknown()";
        };
    }

    private String zodPrimitiveNested(PrimitiveType p) {
        return switch (p) {
            case Int -> "z.number()";
            case Double -> "z.number()";
            case BigInt -> "z.bigint()";
            case String, Date, LocalDate -> "z.string()";
            case Boolean -> "z.boolean()";
            case File -> "z.instanceof(File)";
            case Void -> "z.void()";
            case Unknown -> "z.unknown()";
        };
    }

    private String zodValidation(Validation v) {
        return switch (v) {
            case Validation.Min m -> ".min(" + m.value() + withMessage(m.message()) + ")";
            case Validation.Max m -> ".max(" + m.value() + withMessage(m.message()) + ")";
            // @Size with no explicit max defaults to Integer.MAX_VALUE; emitting it
            // as .max(2147483647) is noise that constrains nothing.
            case Validation.Size s -> ".min(" + s.min() + ")"
                    + (s.max() == Integer.MAX_VALUE ? "" : ".max(" + s.max() + ")");
            case Validation.NotBlank n -> ".regex(/.+/)";
            // Presence only — the constraint is expressed by omitting .optional().
            case Validation.NotNull n -> "";
            case Validation.NotEmpty n -> ".min(1)";
            case Validation.Pattern p -> ".regex(/" + p.regexp() + "/)";
            case Validation.Email e -> ".email(" + messageArg(e.message()) + ")";
        };
    }

    private String withMessage(String message) {
        if (message == null || message.isEmpty()) return "";
        return ", { message: \"" + message + "\" }";
    }

    private String messageArg(String message) {
        if (message == null || message.isEmpty()) return "";
        return "{ message: \"" + message + "\" }";
    }

    private TypeScriptFile generateZodEnum(EnumType e, GeneratorConfig config) {
        TypeScriptFile file = new TypeScriptFile("types/" + e.packageSegment() + "/" + e.name() + ".ts");
        file.getImports().add(new TypeScriptFile.Import("zod", null, Set.of("z")));

        StringBuilder body = new StringBuilder();
        body.append(header(config)).append("\n\n");

        String values = e.values().stream().map(v -> "'" + v + "'").collect(Collectors.joining(", "));
        body.append("export const ").append(e.name()).append("Model = z.enum([").append(values).append("]);\n");
        body.append("export type ").append(e.name())
                .append(" = z.infer<typeof ").append(e.name()).append("Model>;\n");

        file.setBody(body.toString());
        return file;
    }

    /**
     * Walks a validated object's fields and registers a named import for every
     * cross-reference to another Zod-emitted schema ({@code <Name>Model}).
     * <p>
     * Limitation: references to plain (non-validated) object types are *not*
     * registered — the schema body emits {@code <Name>Model} but no such symbol
     * exists in the plain file. To keep a Zod subtree compilable, every
     * cross-referenced ObjectType must also carry at least one validation
     * (or be promoted otherwise). Enums in field position are inlined as
     * {@code z.enum([...])}, so they need no import.
     */
    private void resolveModelImports(TypeScriptFile file, ObjectType obj, Map<String, TypeScriptFile> zodFileByName) {
        Set<String> referenced = new LinkedHashSet<>();
        for (Field field : obj.getFields()) {
            collectObjectReferences(field.type(), referenced);
        }
        for (String name : referenced) {
            if (name.equals(obj.getName())) continue;
            TypeScriptFile target = zodFileByName.get(name);
            if (target == null) continue;
            String importPath = file.resolveImportPath(target);
            file.getImports().add(new TypeScriptFile.Import(importPath, null, Set.of(name + "Model")));
        }
    }

    private void collectObjectReferences(Type type, Set<String> out) {
        switch (type) {
            case ObjectType o -> out.add(o.getName());
            case ArrayType a -> collectObjectReferences(a.subType(), out);
            case MapType m -> {
                collectObjectReferences(m.keyType(), out);
                collectObjectReferences(m.valueType(), out);
            }
            case OptionalType o -> collectObjectReferences(o.subType(), out);
            default -> {}
        }
    }

    private void renderImportsIntoBody(TypeScriptFile file) {
        if (file.getImports().isEmpty()) return;

        StringBuilder importBlock = new StringBuilder();
        for (TypeScriptFile.Import imp : file.getImports()) {
            if (imp.defaultImport() != null && !imp.defaultImport().isEmpty()) {
                importBlock.append("import ").append(imp.defaultImport())
                        .append(" from '").append(imp.path()).append("';\n");
            } else if (imp.namedImports() != null && !imp.namedImports().isEmpty()) {
                importBlock.append("import { ").append(String.join(", ", imp.namedImports()))
                        .append(" } from '").append(imp.path()).append("';\n");
            }
        }

        // Insert imports after the header line so the generator comment stays on top.
        String body = file.getBody();
        int headerEnd = body.indexOf('\n');
        if (headerEnd >= 0) {
            file.setBody(body.substring(0, headerEnd + 1) + importBlock + body.substring(headerEnd + 1));
        }
    }

    private String extractTypeName(String relativePath) {
        String fileName = relativePath.substring(relativePath.lastIndexOf('/') + 1);
        return fileName.replace(".ts", "");
    }

    private String header(GeneratorConfig config) {
        return HEADER + config.headerSuffix();
    }
}
