package ch.adibilis.jtg.writer;

import ch.adibilis.jtg.config.GeneratorConfig;
import ch.adibilis.jtg.model.types.*;

import java.util.*;
import java.util.stream.Collectors;

public class TypeScriptTypeWriter {

    private static final String HEADER = "// Generated by Adibilis Java Type Generator";

    public List<TypeScriptFile> generateTypes(Map<String, Type> namedTypes, GeneratorConfig config) {
        // Build a map of type name -> TypeScriptFile for import resolution
        Map<String, TypeScriptFile> fileMap = new LinkedHashMap<>();
        Map<String, Type> simpleNameToType = new LinkedHashMap<>();
        List<TypeScriptFile> files = new ArrayList<>();

        for (Map.Entry<String, Type> entry : namedTypes.entrySet()) {
            Type type = entry.getValue();
            List<TypeScriptFile> generated = generateType(type, config, namedTypes);
            for (TypeScriptFile file : generated) {
                String simpleName = extractTypeName(file.getRelativePath());
                fileMap.put(simpleName, file);
                simpleNameToType.put(simpleName, type);
                files.add(file);
            }
        }

        // Resolve imports and render them into the body
        for (TypeScriptFile file : files) {
            resolveImports(file, fileMap, simpleNameToType, config);
            renderImportsIntoBody(file);
        }

        return files;
    }

    private List<TypeScriptFile> generateType(Type type, GeneratorConfig config, Map<String, Type> namedTypes) {
        return switch (type) {
            case ObjectType obj -> List.of(generateObjectType(obj, config));
            case EnumType e -> List.of(generateEnumType(e, config));
            case UnionType u -> List.of(generateUnionType(u, config));
            default -> List.of();
        };
    }

    private TypeScriptFile generateObjectType(ObjectType obj, GeneratorConfig config) {
        TypeScriptFile file = new TypeScriptFile("types/" + obj.getName() + ".ts");

        StringBuilder body = new StringBuilder();
        body.append(header(config)).append("\n");

        // Interface declaration
        body.append("\nexport default interface ").append(obj.getName());
        if (!obj.getGenericParams().isEmpty()) {
            body.append("<").append(String.join(", ", obj.getGenericParams())).append(">");
        }
        body.append(" {\n");

        for (Field field : obj.getFields()) {
            String tsType = TypeScriptTypeMapper.map(field.type(), config);
            body.append("    ").append(field.name());
            if (!field.required()) body.append("?");
            body.append(": ").append(tsType).append(";\n");
        }

        body.append("}\n");
        file.setBody(body.toString());
        return file;
    }

    private TypeScriptFile generateEnumType(EnumType e, GeneratorConfig config) {
        TypeScriptFile file = new TypeScriptFile("types/" + e.name() + ".ts");

        StringBuilder body = new StringBuilder();
        body.append(header(config)).append("\n\n");

        String values = e.values().stream().map(v -> "'" + v + "'").collect(Collectors.joining(" | "));
        String valuesArray = e.values().stream().map(v -> "'" + v + "'").collect(Collectors.joining(", "));
        String valuesName = Character.toLowerCase(e.name().charAt(0)) + e.name().substring(1) + "Values";
        body.append("type ").append(e.name()).append(" = ").append(values).append(";\n");
        body.append("export const ").append(valuesName).append(": ").append(e.name()).append("[] = [").append(valuesArray).append("];\n");
        body.append("export default ").append(e.name()).append(";\n");

        file.setBody(body.toString());
        return file;
    }

    private TypeScriptFile generateUnionType(UnionType u, GeneratorConfig config) {
        TypeScriptFile file = new TypeScriptFile("types/" + u.name() + ".ts");

        StringBuilder body = new StringBuilder();
        body.append(header(config)).append("\n\n");

        String variants = u.variants().stream().map(ObjectType::getName).collect(Collectors.joining(" | "));
        body.append("export type ").append(u.name()).append(" = ").append(variants).append(";\n");
        body.append("export default ").append(u.name()).append(";\n");

        file.setBody(body.toString());
        return file;
    }

    private void resolveImports(TypeScriptFile file, Map<String, TypeScriptFile> fileMap,
                                 Map<String, Type> simpleNameToType, GeneratorConfig config) {
        String fileName = extractTypeName(file.getRelativePath());
        Type fileType = simpleNameToType.get(fileName);
        if (fileType == null) return;

        for (Map.Entry<String, TypeScriptFile> entry : fileMap.entrySet()) {
            String typeName = entry.getKey();
            TypeScriptFile targetFile = entry.getValue();
            if (targetFile == file) continue;

            if (bodyReferencesType(fileType, typeName)) {
                String importPath = file.resolveImportPath(targetFile);
                file.getImports().add(new TypeScriptFile.Import(importPath, typeName));
            }
        }
    }

    private boolean bodyReferencesType(Type fileType, String typeName) {
        if (fileType instanceof ObjectType obj) {
            return obj.getFields().stream().anyMatch(f -> fieldReferencesType(f.type(), typeName));
        }
        if (fileType instanceof UnionType u) {
            return u.variants().stream().anyMatch(v -> v.getName().equals(typeName));
        }
        return false;
    }

    private boolean fieldReferencesType(Type type, String typeName) {
        return switch (type) {
            case ObjectType o -> o.getName().equals(typeName) ||
                    o.getGenericArgInstantiations().stream().anyMatch(t -> fieldReferencesType(t, typeName));
            case ArrayType a -> fieldReferencesType(a.subType(), typeName);
            case MapType m -> fieldReferencesType(m.keyType(), typeName) || fieldReferencesType(m.valueType(), typeName);
            case OptionalType o -> fieldReferencesType(o.subType(), typeName);
            case UnionType u -> u.name().equals(typeName);
            case EnumType e -> e.name().equals(typeName);
            default -> false;
        };
    }

    private void renderImportsIntoBody(TypeScriptFile file) {
        if (file.getImports().isEmpty()) return;

        StringBuilder importBlock = new StringBuilder();
        for (TypeScriptFile.Import imp : file.getImports()) {
            if (imp.defaultImport() != null && !imp.defaultImport().isEmpty()) {
                importBlock.append("import ").append(imp.defaultImport())
                        .append(" from '").append(imp.path()).append("';\n");
            } else if (imp.namedImports() != null && !imp.namedImports().isEmpty()) {
                importBlock.append("import { ").append(String.join(", ", imp.namedImports()))
                        .append(" } from '").append(imp.path()).append("';\n");
            }
        }

        // Insert imports after the header line
        String body = file.getBody();
        int headerEnd = body.indexOf('\n');
        if (headerEnd >= 0) {
            file.setBody(body.substring(0, headerEnd + 1) + importBlock + body.substring(headerEnd + 1));
        }
    }

    private String extractTypeName(String relativePath) {
        String fileName = relativePath.substring(relativePath.lastIndexOf('/') + 1);
        return fileName.replace(".ts", "");
    }

    private String header(GeneratorConfig config) {
        return HEADER + config.headerSuffix();
    }
}
