package ch.adibilis.jtg.angular;

import ch.adibilis.jtg.config.GeneratorConfig;
import ch.adibilis.jtg.model.endpoints.*;
import ch.adibilis.jtg.model.types.*;
import ch.adibilis.jtg.writer.*;

import java.util.*;

public class AngularServiceWriter implements Writer {

    private static final String HEADER = "// Generated by Adibilis Java Type Generator";

    @Override
    public List<TypeScriptFile> generate(GeneratorContext context) {
        Map<String, List<Endpoint>> grouped = new LinkedHashMap<>();

        for (Endpoint ep : context.endpoints()) {
            grouped.computeIfAbsent(ep.getClassName(), k -> new ArrayList<>()).add(ep);
        }

        List<TypeScriptFile> files = new ArrayList<>();
        for (Map.Entry<String, List<Endpoint>> entry : grouped.entrySet()) {
            files.add(generateService(entry.getKey(), entry.getValue(), context));
        }
        return files;
    }

    private TypeScriptFile generateService(String controllerName, List<Endpoint> endpoints,
                                            GeneratorContext context) {
        GeneratorConfig config = context.config();
        String serviceName = controllerName.replace("Controller", "");
        String kebabName = toKebabCase(serviceName);
        String packageSegment = serviceName.toLowerCase();

        TypeScriptFile file = new TypeScriptFile("services/" + packageSegment + "/" + kebabName + ".service.ts");

        boolean hasParams = endpoints.stream().anyMatch(ep -> !ep.getParams().isEmpty());
        boolean needsHeaders = endpoints.stream().anyMatch(ep -> ep.getFileParams().isEmpty());

        // Imports
        file.getImports().add(new TypeScriptFile.Import("@angular/core", null, new LinkedHashSet<>(List.of("Injectable", "inject"))));
        if (hasParams) {
            file.getImports().add(new TypeScriptFile.Import("@angular/common/http", null,
                    new LinkedHashSet<>(List.of("HttpClient", "HttpParams"))));
        } else {
            file.getImports().add(new TypeScriptFile.Import("@angular/common/http", null, new LinkedHashSet<>(List.of("HttpClient"))));
        }
        file.getImports().add(new TypeScriptFile.Import("rxjs", null, new LinkedHashSet<>(List.of("Observable"))));
        file.getImports().add(new TypeScriptFile.Import(config.environmentImportPath(), "environment"));

        StringBuilder body = new StringBuilder();
        body.append(HEADER).append(config.headerSuffix()).append("\n");

        // Render import statements
        body.append(renderImports(file));
        body.append("\n");

        if (needsHeaders) {
            body.append("const headers = { 'content-type': 'application/json' };\n\n");
        }

        body.append("@Injectable({\n");
        body.append("    providedIn: 'root',\n");
        body.append("})\n");
        body.append("export class ").append(serviceName).append("Service {\n");
        body.append("    baseURL = environment.serverUrl;\n\n");
        body.append("    private http = inject(HttpClient);\n");

        for (Endpoint ep : endpoints) {
            body.append("\n");
            body.append(buildMethod(ep, config));
        }

        body.append("}\n");

        file.setBody(body.toString());
        return file;
    }

    private String buildMethod(Endpoint ep, GeneratorConfig config) {
        StringBuilder sb = new StringBuilder();
        String returnType = TypeScriptTypeMapper.map(ep.getReturnType(), config);
        boolean hasFileParams = !ep.getFileParams().isEmpty();
        boolean hasQueryParams = !ep.getParams().isEmpty();
        boolean hasBody = ep.getBody() != null;

        // Method signature
        sb.append("    ").append(ep.getMethodName()).append("(");
        sb.append(buildInputs(ep, config));
        sb.append("): Observable<").append(returnType).append("> {\n");

        // FormData for file uploads
        if (hasFileParams) {
            sb.append("        const formData = new FormData();\n");
            for (Field fp : ep.getFileParams()) {
                sb.append("        formData.append('").append(fp.name()).append("', ").append(fp.name()).append(");\n");
            }
        }

        // Query params
        if (hasQueryParams) {
            sb.append(buildParams(ep.getParams(), config));
        }

        // HTTP call
        String httpMethod = ep.getHttpMethod().name().toLowerCase();
        String url = buildUrl(ep);

        sb.append("        return this.http.").append(httpMethod);
        if (!returnType.equals("void")) {
            sb.append("<").append(returnType).append(">");
        }
        sb.append("(\n");
        sb.append("            this.baseURL + `").append(url).append("`");

        // Body argument (for POST, PUT, PATCH)
        if (ep.getHttpMethod() == HttpMethod.POST || ep.getHttpMethod() == HttpMethod.PUT ||
                ep.getHttpMethod() == HttpMethod.PATCH) {
            sb.append(",\n            ");
            if (hasFileParams) {
                sb.append("formData");
            } else if (hasBody) {
                sb.append("body");
            } else {
                sb.append("null");
            }
        }

        // Options
        String options = buildOptions(hasFileParams, hasQueryParams);
        if (!options.isEmpty()) {
            sb.append(",\n            ").append(options);
        }

        sb.append("\n        );\n");
        sb.append("    }\n");

        return sb.toString();
    }

    private String buildInputs(Endpoint ep, GeneratorConfig config) {
        List<String> inputs = new ArrayList<>();

        // URL args (always required)
        for (Field f : ep.getUrlArgs()) {
            inputs.add(f.name() + ": " + TypeScriptTypeMapper.map(f.type(), config));
        }

        // File params
        for (Field fp : ep.getFileParams()) {
            inputs.add(fp.name() + ": File");
        }

        // Body
        if (ep.getBody() != null) {
            inputs.add("body: " + TypeScriptTypeMapper.map(ep.getBody(), config));
        }

        // Required params first, then optional
        List<Field> required = ep.getParams().stream().filter(Field::required).toList();
        List<Field> optional = ep.getParams().stream().filter(f -> !f.required()).toList();

        for (Field f : required) {
            inputs.add(f.name() + ": " + TypeScriptTypeMapper.map(f.type(), config));
        }
        for (Field f : optional) {
            inputs.add(f.name() + "?: " + TypeScriptTypeMapper.map(f.type(), config));
        }

        return String.join(", ", inputs);
    }

    private String buildParams(List<Field> params, GeneratorConfig config) {
        StringBuilder sb = new StringBuilder();
        sb.append("        let params = new HttpParams();\n");

        for (Field param : params) {
            String indent = "        ";
            boolean needsGuard = !param.required();

            if (needsGuard) {
                sb.append(indent).append("if (").append(param.name()).append(") {\n");
                indent = "            ";
            }

            if (param.type() instanceof ArrayType) {
                sb.append(indent).append("params = ").append(param.name())
                        .append(".reduce((p, item) => p.append('").append(param.name()).append("', item), params);\n");
            } else if (param.type() == PrimitiveType.Date && !config.dateAsString()) {
                sb.append(indent).append("params = params.append('").append(param.name())
                        .append("', ").append(param.name()).append(".toISOString());\n");
            } else {
                sb.append(indent).append("params = params.append('").append(param.name())
                        .append("', ").append(param.name()).append(");\n");
            }

            if (needsGuard) {
                sb.append("        }\n");
            }
        }

        return sb.toString();
    }

    private String buildUrl(Endpoint ep) {
        return ep.getUrl().replaceAll("\\{(\\w+)}", "\\${$1}");
    }

    private String buildOptions(boolean hasFileParams, boolean hasQueryParams) {
        if (hasFileParams && hasQueryParams) return "{ params }";
        if (hasFileParams) return "";
        if (hasQueryParams) return "{ headers, params }";
        return "{ headers }";
    }

    private String renderImports(TypeScriptFile file) {
        StringBuilder sb = new StringBuilder();
        for (TypeScriptFile.Import imp : file.getImports()) {
            sb.append("import ");
            if (imp.defaultImport() != null && !imp.defaultImport().isEmpty()) {
                sb.append("{ ").append(imp.defaultImport()).append(" }");
            } else if (imp.namedImports() != null && !imp.namedImports().isEmpty()) {
                sb.append("{ ").append(String.join(", ", imp.namedImports())).append(" }");
            }
            sb.append(" from '").append(imp.path()).append("';\n");
        }
        return sb.toString();
    }

    private String toKebabCase(String name) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < name.length(); i++) {
            char c = name.charAt(i);
            if (Character.isUpperCase(c) && i > 0) {
                sb.append('-');
            }
            sb.append(Character.toLowerCase(c));
        }
        return sb.toString();
    }
}
