package ch.adibilis.jtg.angular;

import ch.adibilis.jtg.config.GeneratorConfig;
import ch.adibilis.jtg.model.endpoints.*;
import ch.adibilis.jtg.model.types.*;
import ch.adibilis.jtg.writer.*;

import java.util.*;

public class AngularServiceWriter implements Writer {

    private static final String HEADER = "// Generated by Adibilis Java Type Generator";
    private static final String UTILS_RELATIVE_PATH = "utils/http-params.ts";

    @Override
    public List<TypeScriptFile> generate(GeneratorContext context) {
        Map<String, List<Endpoint>> grouped = new LinkedHashMap<>();

        for (Endpoint ep : context.endpoints()) {
            grouped.computeIfAbsent(ep.getClassName(), k -> new ArrayList<>()).add(ep);
        }

        List<TypeScriptFile> files = new ArrayList<>();
        for (Map.Entry<String, List<Endpoint>> entry : grouped.entrySet()) {
            files.add(generateService(entry.getKey(), entry.getValue(), context));
        }

        boolean anyQueryParams = context.endpoints().stream().anyMatch(ep -> !ep.getParams().isEmpty());
        if (anyQueryParams) {
            files.add(buildHttpParamsUtilFile(context.config()));
        }

        return files;
    }

    private TypeScriptFile buildHttpParamsUtilFile(GeneratorConfig config) {
        TypeScriptFile file = new TypeScriptFile(UTILS_RELATIVE_PATH);
        file.setHasDefaultExport(false);

        StringBuilder body = new StringBuilder();
        body.append(HEADER).append(config.headerSuffix()).append("\n");
        body.append("import { HttpParams } from '@angular/common/http';\n\n");
        body.append("export function toHttpParams(obj: Record<string, unknown>): HttpParams {\n");
        body.append("    let params = new HttpParams();\n");
        body.append("    for (const [key, value] of Object.entries(obj)) {\n");
        body.append("        if (value === null || value === undefined) continue;\n");
        body.append("        if (value instanceof Date) {\n");
        body.append("            params = params.append(key, value.toISOString());\n");
        body.append("        } else if (Array.isArray(value)) {\n");
        body.append("            params = value.reduce((p: HttpParams, item) => p.append(key, item as string | number | boolean), params);\n");
        body.append("        } else {\n");
        body.append("            params = params.append(key, value as string | number | boolean);\n");
        body.append("        }\n");
        body.append("    }\n");
        body.append("    return params;\n");
        body.append("}\n");

        file.setBody(body.toString());
        return file;
    }

    private TypeScriptFile generateService(String controllerName, List<Endpoint> endpoints,
                                            GeneratorContext context) {
        GeneratorConfig config = context.config();
        String serviceName = controllerName.replace("Controller", "");
        String kebabName = toKebabCase(serviceName);

        TypeScriptFile file = new TypeScriptFile("endpoints/" + kebabName + ".service.ts");

        boolean hasParams = endpoints.stream().anyMatch(ep -> !ep.getParams().isEmpty());
        boolean needsHeaders = endpoints.stream()
                .anyMatch(ep -> ep.getFileParams().isEmpty() || !ep.getHeaders().isEmpty());
        boolean hasResponseVariant = endpoints.stream().anyMatch(Endpoint::isResponseEntity);

        // Collect all referenced type names for imports
        Set<String> referencedTypes = new LinkedHashSet<>();
        for (Endpoint ep : endpoints) {
            collectTypeNames(ep.getReturnType(), referencedTypes);
            if (ep.getBody() != null) {
                collectTypeNames(ep.getBody(), referencedTypes);
            }
            for (Field f : ep.getUrlArgs()) {
                collectTypeNames(f.type(), referencedTypes);
            }
            for (Field f : ep.getParams()) {
                collectTypeNames(f.type(), referencedTypes);
            }
        }

        // Imports
        file.getImports().add(new TypeScriptFile.Import("@angular/core", null, new LinkedHashSet<>(List.of("Injectable", "inject"))));
        Set<String> httpCommonImports = new LinkedHashSet<>();
        httpCommonImports.add("HttpClient");
        if (hasResponseVariant) httpCommonImports.add("HttpResponse");
        file.getImports().add(new TypeScriptFile.Import("@angular/common/http", null, httpCommonImports));
        file.getImports().add(new TypeScriptFile.Import("rxjs", null, new LinkedHashSet<>(List.of("Observable"))));
        file.getImports().add(new TypeScriptFile.Import(config.environmentImportPath(), null, new LinkedHashSet<>(List.of("environment"))));
        if (hasParams) {
            TypeScriptFile utilsStub = new TypeScriptFile(UTILS_RELATIVE_PATH);
            String utilsImportPath = file.resolveImportPath(utilsStub);
            file.getImports().add(new TypeScriptFile.Import(utilsImportPath, null, Set.of("toHttpParams")));
        }

        // Add type imports. Look up each referenced type in the file map produced
        // by the type writers (populated by the Mojo before this writer runs).
        // Falls back to the legacy flat default-import path when the map is empty
        // (e.g. when no type writer ran first, or for an unknown type name).
        Map<String, TypeScriptFile> typeFiles = context.typeFiles();
        for (String typeName : referencedTypes) {
            TypeScriptFile typeFile = typeFiles.get(typeName);
            if (typeFile == null) {
                file.getImports().add(new TypeScriptFile.Import("../types/" + typeName, typeName));
                continue;
            }
            String importPath = file.resolveImportPath(typeFile);
            if (typeFile.hasDefaultExport()) {
                file.getImports().add(new TypeScriptFile.Import(importPath, typeName));
            } else {
                file.getImports().add(new TypeScriptFile.Import(importPath, null, Set.of(typeName)));
            }
        }

        StringBuilder body = new StringBuilder();
        body.append(HEADER).append(config.headerSuffix()).append("\n");

        // Render import statements
        body.append(renderImports(file));
        body.append("\n");

        if (needsHeaders) {
            body.append("const headers = { 'content-type': 'application/json' };\n\n");
        }

        body.append("@Injectable({\n");
        body.append("    providedIn: 'root',\n");
        body.append("})\n");
        body.append("export class ").append(serviceName).append("Service {\n");
        body.append("    baseURL = environment.serverUrl;\n\n");
        body.append("    private http = inject(HttpClient);\n");

        for (Endpoint ep : endpoints) {
            body.append("\n");
            body.append(buildMethod(ep, config, false));
            if (ep.isResponseEntity()) {
                body.append("\n");
                body.append(buildMethod(ep, config, true));
            }
        }

        body.append("}\n");

        file.setBody(body.toString());
        return file;
    }

    private void collectTypeNames(Type type, Set<String> names) {
        switch (type) {
            case ObjectType o -> {
                names.add(o.getName());
                for (Type arg : o.getGenericArgInstantiations()) {
                    collectTypeNames(arg, names);
                }
            }
            case ArrayType a -> collectTypeNames(a.subType(), names);
            case MapType m -> {
                collectTypeNames(m.keyType(), names);
                collectTypeNames(m.valueType(), names);
            }
            case OptionalType o -> collectTypeNames(o.subType(), names);
            case EnumType e -> names.add(e.name());
            case UnionType u -> names.add(u.name());
            default -> {}
        }
    }

    private String buildMethod(Endpoint ep, GeneratorConfig config, boolean withResponse) {
        StringBuilder sb = new StringBuilder();
        String payloadType = TypeScriptTypeMapper.map(ep.getReturnType(), config);
        String observableType = withResponse ? "HttpResponse<" + payloadType + ">" : payloadType;
        boolean hasFileParams = !ep.getFileParams().isEmpty();
        boolean hasQueryParams = !ep.getParams().isEmpty();
        boolean hasBody = ep.getBody() != null;
        boolean hasHeaderParams = !ep.getHeaders().isEmpty();
        String methodName = withResponse ? ep.getMethodName() + "WithResponse" : ep.getMethodName();

        // Method signature
        sb.append("    ").append(methodName).append("(");
        sb.append(buildInputs(ep, config));
        sb.append("): Observable<").append(observableType).append("> {\n");

        // FormData for file uploads
        if (hasFileParams) {
            sb.append("        const formData = new FormData();\n");
            for (Field fp : ep.getFileParams()) {
                sb.append("        formData.append('").append(fp.name()).append("', ").append(fp.name()).append(");\n");
            }
        }

        // Query params
        if (hasQueryParams) {
            sb.append(buildParamsCall(ep.getParams()));
        }

        // Header params
        if (hasHeaderParams) {
            sb.append(buildHeadersVar(ep.getHeaders()));
        }

        // HTTP call
        String httpMethod = ep.getHttpMethod().name().toLowerCase();
        String url = buildUrl(ep);

        sb.append("        return this.http.").append(httpMethod);
        sb.append("<").append(payloadType).append(">");
        sb.append("(\n");
        sb.append("            this.baseURL + `").append(url).append("`");

        // Body argument (for POST, PUT, PATCH)
        if (ep.getHttpMethod() == HttpMethod.POST || ep.getHttpMethod() == HttpMethod.PUT ||
                ep.getHttpMethod() == HttpMethod.PATCH) {
            sb.append(",\n            ");
            if (hasFileParams) {
                sb.append("formData");
            } else if (hasBody) {
                sb.append("body");
            } else {
                sb.append("null");
            }
        }

        // Options
        String options = buildOptions(ep, hasFileParams, hasQueryParams, hasBody, hasHeaderParams, withResponse);
        if (!options.isEmpty()) {
            sb.append(",\n            ").append(options);
        }

        sb.append("\n        );\n");
        sb.append("    }\n");

        return sb.toString();
    }

    private String buildInputs(Endpoint ep, GeneratorConfig config) {
        List<String> inputs = new ArrayList<>();

        // Body first (matches common consumer calling convention)
        if (ep.getBody() != null) {
            inputs.add("body: " + TypeScriptTypeMapper.map(ep.getBody(), config));
        }

        // URL args
        for (Field f : ep.getUrlArgs()) {
            inputs.add(f.name() + ": " + TypeScriptTypeMapper.map(f.type(), config));
        }

        // File params
        for (Field fp : ep.getFileParams()) {
            inputs.add(fp.name() + ": File");
        }

        // Header params and query params share one required/optional partition so the
        // resulting parameter list stays valid TypeScript (required before optional),
        // regardless of which of the two collections a given field came from.
        List<String> required = new ArrayList<>();
        List<String> optional = new ArrayList<>();

        for (HeaderParam h : ep.getHeaders()) {
            addInput(h.field(), config, required, optional);
        }
        for (Field f : ep.getParams()) {
            addInput(f, config, required, optional);
        }

        inputs.addAll(required);
        inputs.addAll(optional);

        return String.join(", ", inputs);
    }

    private void addInput(Field f, GeneratorConfig config, List<String> required, List<String> optional) {
        String type = TypeScriptTypeMapper.map(f.type(), config);
        if (f.required()) {
            required.add(f.name() + ": " + type);
        } else {
            optional.add(f.name() + "?: " + type);
        }
    }

    private String buildParamsCall(List<Field> params) {
        List<String> entries = new ArrayList<>();
        for (Field param : params) {
            if (param.type() instanceof ObjectType) {
                // Spring @ModelAttribute-style expansion: the object's own fields become
                // top-level query keys, so spreading it into the helper's input reproduces
                // the same flat key set the per-field code used to build by hand.
                entries.add("..." + param.name());
            } else {
                entries.add(param.name());
            }
        }
        return "        const params = toHttpParams({ " + String.join(", ", entries) + " });\n";
    }

    private String buildHeadersVar(List<HeaderParam> headerParams) {
        StringBuilder sb = new StringBuilder();
        sb.append("        const requestHeaders: Record<string, string> = { ...headers };\n");
        for (HeaderParam h : headerParams) {
            String accessor = h.field().name();
            if (h.field().required()) {
                sb.append("        requestHeaders['").append(h.headerName()).append("'] = ").append(accessor).append(";\n");
            } else {
                sb.append("        if (").append(accessor).append(") {\n");
                sb.append("            requestHeaders['").append(h.headerName()).append("'] = ").append(accessor).append(";\n");
                sb.append("        }\n");
            }
        }
        return sb.toString();
    }

    private String buildUrl(Endpoint ep) {
        return ep.getUrl().replaceAll("\\{(\\w+)}", "\\${$1}");
    }

    private String buildOptions(Endpoint ep, boolean hasFileParams, boolean hasQueryParams, boolean hasBody,
                                 boolean hasHeaderParams, boolean withResponse) {
        String headersToken = hasHeaderParams ? "headers: requestHeaders" : "headers";
        List<String> parts = new ArrayList<>();

        // DELETE with body: pass body in options since http.delete doesn't take a body argument
        if (ep.getHttpMethod() == HttpMethod.DELETE && hasBody) {
            parts.add(headersToken);
            if (hasQueryParams) parts.add("params");
            parts.add("body");
        } else if (hasFileParams) {
            // Plain file uploads omit headers (the browser sets multipart content-type itself);
            // an endpoint that also declares @RequestHeader params still needs them sent though.
            if (hasHeaderParams) parts.add(headersToken);
            if (hasQueryParams) parts.add("params");
        } else {
            parts.add(headersToken);
            if (hasQueryParams) parts.add("params");
        }

        if (withResponse) parts.add("observe: 'response'");

        if (parts.isEmpty()) return "";
        return "{ " + String.join(", ", parts) + " }";
    }

    private String renderImports(TypeScriptFile file) {
        StringBuilder sb = new StringBuilder();
        for (TypeScriptFile.Import imp : file.getImports()) {
            sb.append("import ");
            if (imp.defaultImport() != null && !imp.defaultImport().isEmpty()) {
                sb.append(imp.defaultImport());
            } else if (imp.namedImports() != null && !imp.namedImports().isEmpty()) {
                sb.append("{ ").append(String.join(", ", imp.namedImports())).append(" }");
            }
            sb.append(" from '").append(imp.path()).append("';\n");
        }
        return sb.toString();
    }

    private String toKebabCase(String name) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < name.length(); i++) {
            char c = name.charAt(i);
            if (Character.isUpperCase(c) && i > 0) {
                sb.append('-');
            }
            sb.append(Character.toLowerCase(c));
        }
        return sb.toString();
    }
}
